# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'simplecov'
require 'vcr'
require 'webmock'

SimpleCov.start do
  add_filter 'config'
  add_filter 'application_controller'
end

VCR.configure do |c|
  c.hook_into                 :webmock
  c.cassette_library_dir      = 'spec/support/vcr_cassettes'
end
#
# require "instagram"
# Instagram.configure do |config|
#   config.client_id = ENV['instagram_id']
#   config.client_secret = ENV['instagram_secret_key']
# end
#
# require 'omniauth'
# OmniAuth.config.test_mode = true
# omniauth_hash = { 'provider' => 'instagram',
#                   'uid' => '12345',
#                   'info' => {
#                     'name' => 'mike',
#                     'email' => 'mike@mike.com',
#                     'nickname' => 'mikedoor',
#                     'website' => 'dorrance.com',
#                     'bio' => 'Way cool!'
#                   },
#                   'credentials' => {'token' =>
#                     1234567890
#                   }
#                 }
#
# OmniAuth.config.add_mock(:instagram, omniauth_hash)
RSpec.configure do |config|
  require 'capybara/rspec'
  require 'database_cleaner'
  require 'simplecov'

  SimpleCov.start 'rails'

  config.include Capybara::DSL

  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do |example|
    DatabaseCleaner.strategy = example.metadata[:js] ? :truncation : :transaction
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

  WebMock.stub_request(:any, "www.localhost:3000")

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|

    mocks.verify_partial_doubles = true
  end

  def user
    @user ||= User.new(name: "Mike Dorrance",
                       nickname: "heshekids",
                       image_url: "happy.jpg",
                       bio: "Cool!",
                       website: "dorrance.com",
                       token: ENV['instagram_test'],
                       uid: "1234",
                       provider: "instagram")
  end

  def login_user
    OmniAuth.config.test_mode = true

    OmniAuth.config.mock_auth[:instagram] = OmniAuth::AuthHash.new ({
      'provider'    => user.provider,
      'uid'         => user.uid,
      'info'        => {:name =>user.name,
                        :nickname =>user.nickname,
                        :bio =>user.bio,
                        :website =>user.website,
                        :image =>user.image_url},
      'credentials' => {:token => ENV['instagram_test']}
    })
  end

end
